#!/usr/bin/env bash

factorize() {
    num=$1
    for ((i=2;i<=num/2;i++)); do
        if ((num%i==0)); then
            echo "$num=$i*$((num/i))"
            return
        fi
    done
    echo "$num=1*$num"
}

if [ $# -ne 1 ]
then
        echo 'Usage: factors <file>'
        exit 1
else
        while read i
        do
                result=$(factorize "$i")
                echo $result
        done < "$1"
fi
