#!/bin/bash

factorize() {
    num=$1
    factors=()
    for ((i = 2; i * i <= num; i++)); do
        while [ $(expr $num % $i) -eq 0 ]; do
            factors+=($i)
            num=$((num / i))
        done
    done

    if [ $num -gt 2 ]; then
        factors+=($num)
    fi

    if [ ${#factors[@]} -eq 2 ]; then
        echo "$num=${factors[0]}*${factors[1]}"
    else
        echo "$num=${factors[*]}"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <number>'
    exit 1
else
    num=$1
    result=$(factorize $num)
    echo "$result"
fi
